// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmI3DsiCYYvKTXldUWpRC39o6gOdRkgxg',
    appId: '1:828377420319:web:3fc1c35e5acdc2de2e3b2a',
    messagingSenderId: '828377420319',
    projectId: 'mmdb-51a60',
    authDomain: 'mmdb-51a60.firebaseapp.com',
    databaseURL: 'https://mmdb-51a60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mmdb-51a60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UEMt4ocbzksgSmF6sKqW-pQ9-0BySk8',
    appId: '1:828377420319:android:603a96a86250d0152e3b2a',
    messagingSenderId: '828377420319',
    projectId: 'mmdb-51a60',
    databaseURL: 'https://mmdb-51a60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mmdb-51a60.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdXFceaBsPHE4frRR9wuntoB-ZPnvQbe4',
    appId: '1:828377420319:ios:ab6d8d30ce034cf92e3b2a',
    messagingSenderId: '828377420319',
    projectId: 'mmdb-51a60',
    databaseURL: 'https://mmdb-51a60-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mmdb-51a60.appspot.com',
    iosClientId: '828377420319-qn3cltii6n7ke11960g12heaa3os5h7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmdbApp',
  );
}
